import setuptools

version = '0.2.1'

with open("aix360/version.py", 'w') as f:
    f.write('# generated by setup.py\nversion = "{}"\n'.format(version))

setuptools.setup(
    name='aix360',
    version=version,
    description='IBM AI Explainability 360',
    authos='aix360 developers',
    url='https://github.com/IBM/AIX360',
    author_email='aix360@us.ibm.com',
    packages=setuptools.find_packages(),
    license='Apache License 2.0',
    long_description=open('README.md', 'r', encoding='utf-8').read(),
    long_description_content_type='text/markdown',
    install_requires=[
            'joblib',
            'scikit-learn',
            'torch',
            'torchvision',
            'cvxpy',
            'Image',
            'tensorflow',
            'h5py',
            'keras',
            'matplotlib',
            'numpy',
            'pandas',
            'scipy',
            'xport',
            'scikit-image',
            'requests',
            'xgboost',
            'bleach',
            'docutils',
            'Pygments',
            'osqp',
            'lime',
            'shap',
            'nyoka',
            'xmltodict',
            'numba',
            'otoc @ git+https://github.com/IBM/otoc@main#egg=otoc'
	],
    package_data={'aix360': ['data/*', 'data/*/*', 'data/*/*/*', 'models/*', 'models/*/*', 'models/*/*/*']},
    include_package_data=True,
    zip_safe=False
)
